export const SM_BUILTIN: Record<string, string> = {
  '/alpha':'α','/beta':'β','/gamma':'γ','/delta':'Δ','/epsilon':'ε','/zeta':'ζ',
  '/eta':'η','/theta':'θ','/iota':'ι','/kappa':'κ','/lambda':'λ','/mu':'μ',
  '/nu':'ν','/xi':'ξ','/pi':'π','/rho':'ρ','/sigma':'σ','/tau':'τ','/phi':'φ',
  '/omega':'ω','/Gamma':'Γ','/Lambda':'Λ','/Sigma':'Σ','/Phi':'Φ','/Omega':'Ω',
  '/chi':'χ','/psi':'ψ','/upsilon':'υ',
  '/sum':'∑','/prod':'∏','/int':'∫','/iint':'∬','/oint':'∮',
  '/sqrt':'√','/cbrt':'∛','/inf':'∞','/approx':'≈','/ne':'≠',
  '/le':'≤','/ge':'≥','/pm':'±','/mp':'∓',
  '/deg':'°','/div':'÷','/mul':'×','/dot':'·','/cdot':'⋅',
  '/any':'∀','/exist':'∃','/nexist':'∄','/in':'∈','/notin':'∉',
  '/subset':'⊂','/supset':'⊃','/subseteq':'⊆','/supseteq':'⊇',
  '/union':'∪','/inter':'∩','/empty':'∅','/partial':'∂','/nabla':'∇',
  '/angle':'∠','/perp':'⊥','/parallel':'∥','/triangle':'△',
  '/lfloor':'⌊','/rfloor':'⌋','/lceil':'⌈','/rceil':'⌉',
  '/therefore':'∴','/because':'∵','/cong':'≅','/sim':'∼','/propto':'∝',
  '/oplus':'⊕','/otimes':'⊗','/circ':'∘',
  '/right':'→','/left':'←','/up':'↑','/down':'↓','/double':'↔',
  '/implies':'⇒','/iff':'⇔','/Leftarrow':'⇐','/Uparrow':'⇑','/Downarrow':'⇓',
  '/mapsto':'↦','/hookright':'↪','/hookleft':'↩',
  '/nearrow':'↗','/nwarrow':'↖','/searrow':'↘','/swarrow':'↙',
  '/copyright':'©','/reg':'®','/tm':'™','/heart':'❤','/check':'✓',
  '/cross':'✗','/star':'★','/bullet':'•','/euro':'€','/pound':'£',
  '/yen':'¥','/section':'§','/para':'¶','/dagger':'†','/ddagger':'‡',
  '/ellipsis':'…','/mdash':'—','/ndash':'–','/laquo':'«','/raquo':'»',
  '/ldquo':'\u201C','/rdquo':'\u201D',
  '/smile':'☺','/frown':'☹','/thumbup':'👍','/thumbdown':'👎',
  '/fire':'🔥','/note':'📝','/warn':'⚠','/info':'ℹ',
  '/^2':'²','/^3':'³','/^n':'ⁿ','/^+':'⁺','/^-':'⁻','/^0':'⁰',
  '/_0':'₀','/_1':'₁','/_2':'₂','/_3':'₃','/_4':'₄','/_5':'₅',
  '/_6':'₆','/_7':'₇','/_8':'₈','/_9':'₉','/_n':'ₙ','/_x':'ₓ','/_a':'ₐ',
  '/1/2':'½','/1/3':'⅓','/1/4':'¼','/2/3':'⅔','/3/4':'¾',
  '/1/8':'⅛','/3/8':'⅜','/5/8':'⅝','/7/8':'⅞',
  '/box':'□','/bbox':'■','/circle':'○','/bcircle':'●','/diamond':'◇','/bdiamond':'◆',
  '/spade':'♠','/club':'♣','/heartsuit':'♥','/diamsym':'♦',
  '/music':'♪','/dmusic':'♫','/phone':'☎','/mail':'✉','/home':'⌂',
  '/sun':'☀','/moon':'☽','/cloud':'☁','/snow':'❄','/umbrella':'☂',
};

export const CATS_BUILTIN: Record<string, string[]> = {
  'Greek Letters':['/alpha','/beta','/gamma','/delta','/epsilon','/zeta','/eta','/theta','/iota','/kappa','/lambda','/mu','/nu','/xi','/pi','/rho','/sigma','/tau','/phi','/chi','/psi','/omega','/upsilon','/Gamma','/Lambda','/Sigma','/Phi','/Omega'],
  'Math Operators':['/sum','/prod','/int','/iint','/oint','/sqrt','/cbrt','/partial','/nabla','/inf','/approx','/ne','/le','/ge','/pm','/mp','/deg','/div','/mul','/dot','/cdot','/circ','/oplus','/otimes'],
  'Set Theory':['/any','/exist','/nexist','/in','/notin','/subset','/supset','/subseteq','/supseteq','/union','/inter','/empty'],
  'Geometry':['/angle','/perp','/parallel','/triangle','/lfloor','/rfloor','/lceil','/rceil','/cong','/sim','/propto','/therefore','/because'],
  'Arrows':['/right','/left','/up','/down','/double','/implies','/iff','/Leftarrow','/Uparrow','/Downarrow','/mapsto','/hookright','/hookleft','/nearrow','/nwarrow','/searrow','/swarrow'],
  'Superscripts':['/^0','/^2','/^3','/^n','/^+','/^-'],
  'Subscripts':['/_0','/_1','/_2','/_3','/_4','/_5','/_6','/_7','/_8','/_9','/_n','/_x','/_a'],
  'Fractions':['/1/2','/1/3','/1/4','/2/3','/3/4','/1/8','/3/8','/5/8','/7/8'],
  'Shapes':['/box','/bbox','/circle','/bcircle','/diamond','/bdiamond'],
  'Card Suits':['/spade','/club','/heartsuit','/diamsym'],
  'Weather & Nature':['/sun','/moon','/cloud','/snow','/umbrella'],
  'Music & Communication':['/music','/dmusic','/phone','/mail','/home'],
  'Misc':['/copyright','/reg','/tm','/heart','/check','/cross','/star','/bullet','/euro','/pound','/yen','/section','/para','/dagger','/ddagger','/ellipsis','/mdash','/ndash','/laquo','/raquo','/ldquo','/rdquo','/smile','/frown','/thumbup','/thumbdown','/fire','/note','/warn','/info'],
};

export const NAMES_BUILTIN: Record<string, string> = {
  '/alpha':'alpha','/beta':'beta','/gamma':'gamma','/delta':'delta','/epsilon':'epsilon',
  '/theta':'theta','/pi':'pi','/sigma':'sigma','/phi':'phi','/omega':'omega',
  '/chi':'chi','/psi':'psi','/lambda':'lambda','/mu':'mu',
  '/sum':'summation','/prod':'product','/int':'integral','/iint':'double integral','/oint':'contour integral',
  '/sqrt':'square root','/cbrt':'cube root','/inf':'infinity',
  '/approx':'approx equal','/ne':'not equal','/le':'less or equal','/ge':'greater or equal',
  '/pm':'plus minus','/mp':'minus plus','/deg':'degree','/div':'divide','/mul':'multiply',
  '/cdot':'center dot','/circ':'composition',
  '/any':'for all','/exist':'there exists','/nexist':'does not exist',
  '/in':'element of','/notin':'not element of','/subset':'subset','/supset':'superset',
  '/union':'union','/inter':'intersection','/empty':'empty set',
  '/partial':'partial','/nabla':'nabla','/angle':'angle','/perp':'perpendicular',
  '/parallel':'parallel','/triangle':'triangle','/therefore':'therefore','/because':'because',
  '/cong':'congruent','/sim':'similar','/propto':'proportional',
  '/right':'right arrow','/left':'left arrow','/up':'up arrow','/down':'down arrow',
  '/double':'double arrow','/implies':'implies','/iff':'if and only if',
  '/mapsto':'maps to','/hookright':'hook right',
  '/heart':'heart','/check':'check mark','/cross':'cross','/star':'star',
  '/euro':'euro','/pound':'pound','/yen':'yen','/section':'section',
  '/bullet':'bullet','/ellipsis':'ellipsis','/mdash':'em dash','/ndash':'en dash',
  '/copyright':'copyright','/reg':'registered','/tm':'trademark',
  '/smile':'smile','/frown':'frown','/fire':'fire','/warn':'warning','/info':'info',
  '/box':'empty box','/bbox':'filled box','/circle':'empty circle','/bcircle':'filled circle',
  '/spade':'spade','/club':'club','/heartsuit':'heart suit','/diamsym':'diamond',
  '/sun':'sun','/moon':'moon','/cloud':'cloud','/snow':'snowflake',
  '/music':'music note','/phone':'phone','/mail':'envelope','/home':'home',
  '/1/2':'one half','/1/3':'one third','/1/4':'one quarter','/2/3':'two thirds','/3/4':'three quarters',
};
